### ISSUE TITLE
Difficulty with subtitling

### ISSUE THREAD

**Issue by Thiagobhmg** [geekodour/wscribe#1]
Hello, can you help me? I'm using wscribe to generate subtitles for lectures. However, I'm encountering a difficulty.The sentence breaks are not being made at the pauses, it seems that Whisper is using the entire sentence to generate the speech. Is there any parameter that can correct this? So that the breaks respect the speaking time?

**Comment by geekodour** [comment]
I am not sure if I understand the issue you're describing correctly, can you provide me with the sample output and the media file and what you're expecting the output to be so that I can re-produce the issue?

**Comment by Thiagobhmg** [comment]
I actually managed to solve the problem using fast-whisper's --vad_filter directly with fast-whisper. I believe you would have to enable --vad_filter since you are using fast-whisper as the basis for your project.

The problem was that wscribe was not breaking the caption lines correctly. With VAD enabled it will better detect what is human mouth and every time there is a pause it breaks the subtitle. It's perfect!

**Comment by geekodour** [comment]
great! happy that you got your setup working! I've mean meaning to add vad filter to wscribe, shall do it soon :)
